version: "3.1"

services:

  db:
    image: postgres
    container_name: dashboard_postgress
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty#dash
      POSTGRES_USER: dashboard
      POSTGRES_DB: naumen_db
      PGDATE: ./postgres/data
      POOSTGRES_INITDB_ARGS: "-A md5"
    expose:
      - 5432

  redis:
    container_name: dashboard_redis
    image: redis
    restart: always
    ports:
      - "16379:6379"

  webapp:
    container_name: dashboard_gunicorn
    restart: always
    volumes:
      - .static:/static
    env_file:
      - .env
    build:
      dockerfile: Dockerfile.django
      context: .
    expose:
      - 8000

  nginx:
    container_name: dashboard_nginx
    build: ./nginx
    volumes:
      - .static:/static
    ports:
      - "80:80"
    depends_on:
      - webapp
