version: "3.1"

services:

  db:
    image: postgres
    container_name: dashboard_postgress
    restart: always
    env_file:
      - .env.db
    volumes:
      - .:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    container_name: dashboard_redis
    image: redis
    restart: always

  webapp:
    container_name: dashboard_webapp
    restart: always
    volumes:
      - .static:/static
    env_file:
      - .env
    build:
      dockerfile: Dockerfile.webapp
      context: .
    expose:
      - 8000

  celery_worker:
    container_name: celery_worker
    restart: always
    volumes:
      - .static:/static
    env_file:
      - .env
    build:
      dockerfile: Dockerfile.celery_worker
      context: .

  celery_beat:
    container_name: celery_beat
    restart: always
    volumes:
      - .static:/static
    env_file:
      - .env
    build:
      dockerfile: Dockerfile.celery_beat
      context: .

  nginx:
    container_name: dashboard_nginx
    build: ./nginx
    volumes:
      - .static:/static
    ports:
      - "80:80"
    depends_on:
      - webapp
