FROM python:3.9
ENV PYTHONUNBUFFERED 1

RUN apt-get update -y && apt-get upgrade -y

WORKDIR /app

RUN pip install -U pip

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY ./src .

CMD [ "celery", "-A", "clamp", "worker" ]