FROM python:3.9
ENV PYTHONUNBUFFERED 1

RUN apt-get update -y && apt-get upgrade -y

WORKDIR /app

RUN pip install -U pip

COPY ./requirements.txt ./

RUN pip install -r requirements.txt
RUN git clone https://github.com/catemohi/naumen_api.git
RUN python3 naumen_api/setup.py install

COPY ./src .
COPY .venv/config.json .

CMD [ "celery", "-A", "clamp", "worker", "-B", '-l', 'INFO', "-Q", "naumen_crud", "--concurrency=1" ]