version: '3'
services:
  db:
    image: postgres
    container_name: dashboard_postgress
    restart: always
    env_file:
      - .env.db
    volumes:
      - .:/var/lib/postgresql/data
    expose:
      - 5432
  redis:
    container_name: dashboard_redis    
    image: redis
    depend_on:
      - db
    restart: always
  webapp:
    container_name: dashboard_webapp
    depend_on:
      - db
    restart: always
    volumes:
      - .static:/static
      - .media:/media
    env_file:
      - .env
    build:
      dockerfile: Dockerfile.webapp
      context: .
    expose:
      - 8000
  celery_worker:
    container_name: celery_worker
    restart: always
    depend_on:
      - webapp    
    volumes:
      - .static:/static
      - .media:/media
    env_file:
      - .env
    build:
      dockerfile: Dockerfile.celery_worker
      context: .
  celery_beat:
    container_name: celery_beat
    depend_on:
      - webapp
    restart: always
    volumes:
      - .static:/static
      - .media:/media
    env_file:
      - .env
    build:
      dockerfile: Dockerfile.celery_beat
      context: .
  nginx:
    container_name: dashboard_nginx
    build: ./nginx
    volumes:
      - .static:/static
      - .media:/media
    ports:
      - "80:80"
    depends_on:
      - webapp
